/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubType = IDL.Variant({
  'parallelRct' : IDL.Null,
  'nonInferiorityTrial' : IDL.Null,
  'compareTwoMeans' : IDL.Null,
  'estimateMean' : IDL.Null,
  'crossoverTrial' : IDL.Null,
  'estimateProportion' : IDL.Null,
  'compareTwoProportionsCaseControl' : IDL.Null,
  'compareTwoProportionsCohort' : IDL.Null,
});
export const StudyType = IDL.Variant({
  'descriptive' : IDL.Null,
  'clinicalTrial' : IDL.Null,
  'analytic' : IDL.Null,
});
export const Calculation = IDL.Record({
  'id' : IDL.Nat,
  'subType' : SubType,
  'resultN' : IDL.Float64,
  'studyType' : StudyType,
  'timestamp' : IDL.Int,
  'inputDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCalculationById' : IDL.Func([IDL.Nat], [Calculation], ['query']),
  'getRecentCalculations' : IDL.Func([], [IDL.Vec(Calculation)], ['query']),
  'saveCalculation' : IDL.Func(
      [StudyType, SubType, IDL.Text, IDL.Float64, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubType = IDL.Variant({
    'parallelRct' : IDL.Null,
    'nonInferiorityTrial' : IDL.Null,
    'compareTwoMeans' : IDL.Null,
    'estimateMean' : IDL.Null,
    'crossoverTrial' : IDL.Null,
    'estimateProportion' : IDL.Null,
    'compareTwoProportionsCaseControl' : IDL.Null,
    'compareTwoProportionsCohort' : IDL.Null,
  });
  const StudyType = IDL.Variant({
    'descriptive' : IDL.Null,
    'clinicalTrial' : IDL.Null,
    'analytic' : IDL.Null,
  });
  const Calculation = IDL.Record({
    'id' : IDL.Nat,
    'subType' : SubType,
    'resultN' : IDL.Float64,
    'studyType' : StudyType,
    'timestamp' : IDL.Int,
    'inputDescription' : IDL.Text,
  });
  
  return IDL.Service({
    'getCalculationById' : IDL.Func([IDL.Nat], [Calculation], ['query']),
    'getRecentCalculations' : IDL.Func([], [IDL.Vec(Calculation)], ['query']),
    'saveCalculation' : IDL.Func(
        [StudyType, SubType, IDL.Text, IDL.Float64, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };