/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Calculation {
    id: bigint;
    subType: SubType;
    resultN: number;
    studyType: StudyType;
    timestamp: bigint;
    inputDescription: string;
}
export enum StudyType {
    descriptive = "descriptive",
    clinicalTrial = "clinicalTrial",
    analytic = "analytic"
}
export enum SubType {
    parallelRct = "parallelRct",
    nonInferiorityTrial = "nonInferiorityTrial",
    compareTwoMeans = "compareTwoMeans",
    estimateMean = "estimateMean",
    crossoverTrial = "crossoverTrial",
    estimateProportion = "estimateProportion",
    compareTwoProportionsCaseControl = "compareTwoProportionsCaseControl",
    compareTwoProportionsCohort = "compareTwoProportionsCohort"
}
export interface backendInterface {
    getCalculationById(id: bigint): Promise<Calculation>;
    getRecentCalculations(): Promise<Array<Calculation>>;
    saveCalculation(studyType: StudyType, subType: SubType, inputDescription: string, resultN: number, timestamp: bigint): Promise<void>;
}
import type { Calculation as _Calculation, StudyType as _StudyType, SubType as _SubType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getCalculationById(arg0: bigint): Promise<Calculation> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalculationById(arg0);
                return from_candid_Calculation_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalculationById(arg0);
            return from_candid_Calculation_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentCalculations(): Promise<Array<Calculation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentCalculations();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentCalculations();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCalculation(arg0: StudyType, arg1: SubType, arg2: string, arg3: number, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCalculation(to_candid_StudyType_n8(this._uploadFile, this._downloadFile, arg0), to_candid_SubType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCalculation(to_candid_StudyType_n8(this._uploadFile, this._downloadFile, arg0), to_candid_SubType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_Calculation_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Calculation): Calculation {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_StudyType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyType): StudyType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SubType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubType): SubType {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    subType: _SubType;
    resultN: number;
    studyType: _StudyType;
    timestamp: bigint;
    inputDescription: string;
}): {
    id: bigint;
    subType: SubType;
    resultN: number;
    studyType: StudyType;
    timestamp: bigint;
    inputDescription: string;
} {
    return {
        id: value.id,
        subType: from_candid_SubType_n3(_uploadFile, _downloadFile, value.subType),
        resultN: value.resultN,
        studyType: from_candid_StudyType_n5(_uploadFile, _downloadFile, value.studyType),
        timestamp: value.timestamp,
        inputDescription: value.inputDescription
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    parallelRct: null;
} | {
    nonInferiorityTrial: null;
} | {
    compareTwoMeans: null;
} | {
    estimateMean: null;
} | {
    crossoverTrial: null;
} | {
    estimateProportion: null;
} | {
    compareTwoProportionsCaseControl: null;
} | {
    compareTwoProportionsCohort: null;
}): SubType {
    return "parallelRct" in value ? SubType.parallelRct : "nonInferiorityTrial" in value ? SubType.nonInferiorityTrial : "compareTwoMeans" in value ? SubType.compareTwoMeans : "estimateMean" in value ? SubType.estimateMean : "crossoverTrial" in value ? SubType.crossoverTrial : "estimateProportion" in value ? SubType.estimateProportion : "compareTwoProportionsCaseControl" in value ? SubType.compareTwoProportionsCaseControl : "compareTwoProportionsCohort" in value ? SubType.compareTwoProportionsCohort : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    descriptive: null;
} | {
    clinicalTrial: null;
} | {
    analytic: null;
}): StudyType {
    return "descriptive" in value ? StudyType.descriptive : "clinicalTrial" in value ? StudyType.clinicalTrial : "analytic" in value ? StudyType.analytic : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Calculation>): Array<Calculation> {
    return value.map((x)=>from_candid_Calculation_n1(_uploadFile, _downloadFile, x));
}
function to_candid_StudyType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyType): _StudyType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SubType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubType): _SubType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubType): {
    parallelRct: null;
} | {
    nonInferiorityTrial: null;
} | {
    compareTwoMeans: null;
} | {
    estimateMean: null;
} | {
    crossoverTrial: null;
} | {
    estimateProportion: null;
} | {
    compareTwoProportionsCaseControl: null;
} | {
    compareTwoProportionsCohort: null;
} {
    return value == SubType.parallelRct ? {
        parallelRct: null
    } : value == SubType.nonInferiorityTrial ? {
        nonInferiorityTrial: null
    } : value == SubType.compareTwoMeans ? {
        compareTwoMeans: null
    } : value == SubType.estimateMean ? {
        estimateMean: null
    } : value == SubType.crossoverTrial ? {
        crossoverTrial: null
    } : value == SubType.estimateProportion ? {
        estimateProportion: null
    } : value == SubType.compareTwoProportionsCaseControl ? {
        compareTwoProportionsCaseControl: null
    } : value == SubType.compareTwoProportionsCohort ? {
        compareTwoProportionsCohort: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyType): {
    descriptive: null;
} | {
    clinicalTrial: null;
} | {
    analytic: null;
} {
    return value == StudyType.descriptive ? {
        descriptive: null
    } : value == StudyType.clinicalTrial ? {
        clinicalTrial: null
    } : value == StudyType.analytic ? {
        analytic: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
